//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhaSach
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuiDinh
    {
        public string MaQD { get; set; }
        public string TenQD { get; set; }
        public Nullable<int> GiaTri { get; set; }
        public Nullable<int> SuDung { get; set; }
    }
}
